apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cvmfsd
  namespace: {{ $.Release.Namespace }}
  labels:
    app: cvmfsd
    kubernetes.io/cluster-service: "true"
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
      matchLabels:
        app: cvmfsd
  template:
    metadata:
      labels:
        app: cvmfsd
        kubernetes.io/cluster-service: "true"
      annotations:
        # update on configmap change
        checksum/config-map: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: cvmfsd
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
              - NET_ADMIN
        volumeMounts:
          - name: cvmfs-config
            mountPath: /root/cvmfs_default.local # should be /etc/cvmfs/default.local but sciencebox overwrites it
            subPath: default.local
          - name: cvmfs-config
            mountPath: /etc/supercronic.d/cvmfs_prefetch.sh
            subPath: cvmfs_prefetch.sh
          - name: dev-fuse
            mountPath: /dev/fuse
          - name: var-cvmfs
            mountPath: /cvmfs
            mountPropagation: Bidirectional
        env:
          - name: PODINFO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: PODINFO_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PODINFO_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PODINFO_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: PODINFO_NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: THIS_CONTAINER
            value: "CVMFS"
          - name: DEPLOYMENT_TYPE
            value: "kubernetes"
          - name: CVMFS_FOLDER
            value: "/cvmfs"
        lifecycle:
          preStop:
            exec:
              command: ["bash", "/root/stop.sh"]
        resources:
          limits:
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 200Mi
      volumes:
        - name: cvmfs-config
          configMap:
            name: cvmfs-config
            items:
            - key: cvmfs_prefetch.sh
              path: cvmfs_prefetch.sh
            - key: default.local
              path: default.local
        - name: dev-fuse
          hostPath:
            path: /dev/fuse
        - name: var-cvmfs
          hostPath:
            path: /var/cvmfs
