kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: swan
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["secrets", "services"]
    verbs: ["get", "watch", "list", "create", "delete", "update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: swan
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: hub
roleRef:
  kind: Role
  name: swan
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodes-list
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
subjects:
- kind: ServiceAccount
  name: notifications-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: pods-list
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodes-list
subjects:
- kind: ServiceAccount
  name: notifications-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: nodes-list
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notifications-sa
  namespace: {{ .Release.Namespace }}
